comedylib/apps/accounts/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, url, include
from django.contrib.auth.views import logout

from registration.views import register

from accounts.forms import CustomAuthForm, SignUpForm
from accounts.views import login

urlpatterns = patterns('',
    url('^login/$', login,
        {'authentication_form': CustomAuthForm},
        name='accounts_login'),
    url('^logout/$', logout,
        {'next_page': settings.LOGOUT_REDIRECT_URL},
        name='accounts_logout'),
    url(r'^register/$',
        register,
        {'backend': 'registration.backends.default.DefaultBackend',
         'form_class': SignUpForm},
        name='accounts_register'),

    url('^', include('registration.backends.default.urls')),
    url('^', include('social_auth.urls')),
)

comedylib/apps/content/urls.py
from django.conf.urls.defaults import patterns, url

from content.views import (Home, About, CollectionList,
                           CollectionDetail, VideoDetail, Playlists)

urlpatterns = patterns('',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^comedians/$', CollectionList.as_view(), {'role': 0},
        name='comedians'),
    url(r'^comedians/(?P<slug>[a-z0-9-]+)-(?P<pk>\d+)$',
        CollectionDetail.as_view(),
        name='comedian'),

    url(r'^shows/$', CollectionList.as_view(), {'role': 1},
        name='shows'),
    url(r'^shows/(?P<slug>[a-z0-9-]+)-(?P<pk>\d+)$',
        CollectionDetail.as_view(),
        name='show'),

    url(r'^movies/$', CollectionList.as_view(), {'role': 2},
        name='movies'),
    url(r'^movies/(?P<slug>[a-z0-9-]+)-(?P<pk>\d+)$',
        CollectionDetail.as_view(),
        name='movie'),

    url(r'^(?:comedians|shows|movies)/.*?/(?P<pk>\d+)',
        VideoDetail.as_view(),
        name='video'),
    url(r'^playlists/$', Playlists.as_view(), name='playlists'),
)

comedylib/apps/feedback/urls.py
from django.conf.urls import include, patterns, url

from contact_form.views import ContactFormView

from feedback.forms import FeedbackForm


urlpatterns = patterns('',
    url(r'^$', ContactFormView.as_view(form_class=FeedbackForm),
        name='contact_form'),
    url(r'^', include('contact_form.urls')),
)

comedylib/urls.py
"""
Global project URLs
"""
from django.conf import settings
from django.conf.urls.defaults import patterns, url, include
from django.conf.urls.static import static
from django.contrib import admin

from haystack.forms import SearchForm
from haystack.views import search_view_factory

from search.views import CustomSearchView

admin.autodiscover()

flatpages_urls = patterns('django.contrib.flatpages.views',
    url(r'^about/$', 'flatpage', {'url': '/about/'}, name='about'),
    url(r'^terms/$', 'flatpage', {'url': '/terms/'}, name='terms'),
    url(r'^privacy/$', 'flatpage', {'url': '/privacy/'}, name='privacy'),
    url(r'^ads/$', 'flatpage', {'url': '/ads/'}, name='ads'),
)

urlpatterns = patterns('',
    url(r'^a52/', include(admin.site.urls)),
    url(r'^a/', include('accounts.urls')),
    url(r'^u/', include('profiles.urls')),
    url(r'^c/', include('django.contrib.comments.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^search/', search_view_factory(
        view_class=CustomSearchView,
        form_class=SearchForm,
        ), name='haystack_search'),
    url(r'^com/', include('affiliates.urls', namespace='affiliates')),
    url(r'^', include(flatpages_urls, namespace='flatpages')),
    url(r'^', include('content.urls', namespace='content')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

comedylib/apps/affiliates/models.py
from django.db import models

# Create your models here.

comedylib/apps/content/models.py
import datetime
import os
import random
from urllib2 import urlparse

from django.conf import settings
from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from south.modelsinspector import add_ignored_fields

from content.forms import CustomTaggableManager
from comedylib.mixins import CreatedMixin


# We make South ignore this custom field
add_ignored_fields(["^content\.forms\.CustomTaggableManager"])


class Collection(CreatedMixin):
    ROLE_CHOICES = (
        (0, u'comedian'),
        (1, u'show'),
        (2, u'movie'),
    )
    name = models.CharField(max_length=255)
    picture = models.ImageField(upload_to='collections')
    description = models.TextField()
    connections = models.ManyToManyField('self', related_name='connections',
                                         blank=True)
    role = models.SmallIntegerField(choices=ROLE_CHOICES)
    slug = models.SlugField(max_length=100, blank=True)
    tags = CustomTaggableManager(help_text = _("Choose one or more tags."))

    def __unicode__(self):
        return u"%s | %s" % (self.name, self.get_role_display())

    @models.permalink
    def get_absolute_url(self):
        return ('content:%s' % self.get_role_display(), (self.slug, self.id))

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Collection, self).save(*args, **kwargs)

    @property
    def rating(self):
        ratings = [v.rating for v in self.videos.all() if v.rating != 0]
        if len(ratings) == 0:
            return 0
        return sum(ratings) / len(ratings)

    @property
    def votes(self):
        return sum(v.votes for v in self.videos.all())


class VideoManager(models.Manager):
    use_for_related_fields = True

    def playlist_order(self):
        """
        Used when we retrieve all videos of a playlist. Returns the videos
        in the order specified in the playlist.
        """
        return self.all().order_by('playlistvideo__order')


class Video(CreatedMixin):
    title = models.CharField(max_length=255)
    url = models.URLField()
    duration = models.CharField(max_length=20,
                                help_text='Format hh:mm:ss or mm:ss')
    views = models.IntegerField(default=0)
    collection = models.ForeignKey(Collection, related_name='videos')
    VID_THUMB_DUMMY = os.path.join(settings.STATIC_URL, 'img/dumvid.jpg')
    picture = models.ImageField(upload_to='videos', null=True, blank=True,
                                default=VID_THUMB_DUMMY)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    STATUS_CHOICES = (
        (0, u'private'),
        (1, u'public'),
    )
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=1,
                                      blank=True)
    objects = VideoManager()

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return u"%s | %s | %s" % (self.title, self.collection.name,
                                  "%s..." % self.url[:50]
                                  if len(self.url) > 50 else self.url)

    def get_absolute_url(self):
        coll_url = reverse('content:%s' % self.collection.get_role_display(),
                           args=[self.collection.slug, self.collection.id])
        return '%s/%s' % (coll_url, self.id)

    @property
    def rating(self):
        likes = self.likes
        dislikes = self.dislikes
        if (likes + dislikes) == 0:
            return 0
        return (100 * likes) / (likes + dislikes)

    @property
    def votes(self):
        return self.likes + self.dislikes

    @property
    def youtube_id(self):
        url_params = urlparse.urlparse(self.url).query
        try:
            return urlparse.parse_qs(url_params)['v'][0]
        except (KeyError, IndexError):
            return None


class FeaturedManager(models.Manager):
    """
    Overrides the default manager's `get` method, to create
    the `Featured` instance (which is a singleton), in case it
    doesn't exist
    """
    def __init__(self, *args, **kwargs):
        # We set the key on the manager, so that we can use it
        # in the management command
        self.cache_key = 'featured_colls'
        super(FeaturedManager, self).__init__(*args, **kwargs)

    def get(self, *args, **kwargs):
        instance = cache.get(self.cache_key)
        if instance is not None:
            return instance

        try:
            instance = super(FeaturedManager, self).get(*args, **kwargs)
        except self.model.DoesNotExist:
            instance = self._create()

        # We cache for 24 hours
        cache.set(self.cache_key, instance, 60 * 60 * 24)
        return instance

    def _create(self):
        kwargs = {}
        for role_id, role_name in Collection.ROLE_CHOICES:
            new_objs = Collection.objects.filter(role=role_id)
            if not new_objs:
                return
            kwargs[role_name] = random.choice(new_objs)
        instance = self.create(**kwargs)
        return instance


class Featured(models.Model):
    comedian = models.OneToOneField(Collection, related_name='+')
    show = models.OneToOneField(Collection, related_name='+')
    movie = models.OneToOneField(Collection, related_name='+')
    updated = models.DateTimeField(blank=True)
    instance = FeaturedManager()

    def save(self, *args, **kwargs):
        self.updated = datetime.datetime.utcnow()
        super(Featured, self).save(*args, **kwargs)

comedylib/apps/profiles/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.template.defaultfilters import slugify

from comedylib.mixins import CreatedMixin
from content.models import Collection, Video


class Profile(models.Model):
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    user = models.OneToOneField(User)
    feelings = models.ManyToManyField(Video, through='Feeling', null=True)
    picture = models.ImageField(upload_to='profiles', blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES,
                              blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)

    def __unicode__(self):
        return u"%s: %s playlists" % (self.user.username,
                                      self.playlists.all().count())

    @models.permalink
    def get_absolute_url(self):
        return('user_home', (self.user.id,))


class Playlist(CreatedMixin):
    profile = models.ForeignKey(Profile, related_name='playlists')
    videos = models.ManyToManyField(Video, through='PlaylistVideo',
                                    related_name='playlists', null=True)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=100, blank=True)
    empty = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return u"%s: %s videos" % (self.title, self.profile.user.username)

    @models.permalink
    def get_absolute_url(self):
        return('playlist', (self.slug, self.id))

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Playlist, self).save(*args, **kwargs)

    @property
    def bookmarks_count(self):
        cache_key = 'pl_bmk_count_%s' % (self.pk,)
        count = cache.get(cache_key)
        if count is not None:
            return count

        count = Bookmark.objects.filter(
            content_type=ContentType.objects.get(name='playlist'),
            object_id=self.pk
        ).count()

        cache.set(cache_key, count, 60 * 60)
        return count


class PlaylistVideo(models.Model):
    playlist = models.ForeignKey(Playlist)
    video = models.ForeignKey(Video)
    order = models.IntegerField(null=True)


class Feeling(CreatedMixin):
    NAME_CHOICES = (
        ('L', 'like'),
        ('D', 'dislike'),
    )
    profile = models.ForeignKey(Profile)
    video = models.ForeignKey(Video, related_name='feelings')
    name = models.CharField(max_length=5, choices=NAME_CHOICES)

    class Meta:
        unique_together = ('profile', 'video')


class Bookmark(models.Model):
    profile = models.ForeignKey(Profile, related_name='bookmarks')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    post = generic.GenericForeignKey('content_type', 'object_id')

    class Meta:
        unique_together = ('profile', 'content_type', 'object_id')

    def __unicode__(self):
        return u"%s: %s" % (self.profile.user.username, self.post)


class RelevantLink(models.Model):
    collection = models.ForeignKey(Collection, related_name='relevant_links')
    title = models.CharField(max_length=255)
    # Using a CharField instead of an URL field, because we put
    # relative paths in the field, which URLField doesn't accept
    url = models.CharField(max_length=255)
    order = models.IntegerField()

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return u"%s: %s" % (self.collection.name, self.title)


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    user = kwargs.get('instance')
    try:
        user.profile
    except Profile.DoesNotExist:
        Profile.objects.create(user=user)


@receiver(post_save, sender=Playlist.videos.through)
def mark_pl_as_not_empty(sender, **kwargs):
    playlist = kwargs.get('instance').playlist
    if playlist.empty:
        playlist.empty = False
        playlist.save()


@receiver(pre_delete, sender=Playlist.videos.through)
def mark_pl_as_empty(sender, **kwargs):
    playlist = kwargs.get('instance').playlist
    if playlist.videos.count() == 1:
        playlist.empty = True
        playlist.save()

comedylib/apps/feedback/forms.py
from contact_form.forms import ContactForm


class FeedbackForm(ContactForm):
    from_email = 'feedback@comedylib.com'

comedylib/apps/profiles/forms.py
from django import forms

from profiles.models import Playlist, Profile


class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ('title',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user', 'feelings')

comedylib/apps/accounts/views.py
from django.contrib.auth.views import login as auth_login

def login(request, *args, **kwargs):
    if request.method == 'POST':
        if not request.POST.get('remember', False):
            request.session.set_expiry(0)
    return auth_login(request, *args, **kwargs)

comedylib/apps/affiliates/views.py
import json

from django.http import HttpResponse
from django.views.generic import View

from affiliates.search import offer_searcher


class Offers(View):
    def get(self, *args, **kwargs):
        keyword = self.request.GET.get('keyword')
        if keyword is not None:
            offers = offer_searcher.search(keyword, no_of_results=2)
        else:
            return HttpResponse(
                json.dumps({'status': 'ERROR', 'msg': 'Missing keyword'}),
                content_type='application/json',
            )
        return HttpResponse(json.dumps(offers), content_type='application/json')

comedylib/apps/search/views.py
from haystack.views import SearchView


class CustomSearchView(SearchView):
    """
    Adds the 'page' context object under the name of 'page_obj' as well,
    so that the view can use the pagination template.
    """
    def extra_context(self):
        (paginator, page) = self.build_page()
        return {'page_obj': page}

comedylib/templates/profiles/bookmarks.html
{% extends "profiles/home.html" %}
{% block title %}Comedylib - Bookmarked {{post_type}}s of {{user.username}}{% endblock %}
{% block profile_content %}
{% load thumbnail %}
<div class="col-xs-12 col-sm-10">
    <h5>Bookmarked {{ post_type }}s</h5>
        {% if post_type == 'Video' %}
        <ul class="bookmarks">  
        {% for bookmark in bookmarks %}
            <li class="collection-content">
                <div class="row">
                    <a href="{{ bookmark.post.get_absolute_url }}" class="col-xs-12">
                        <img src="{% thumbnail bookmark.post.picture 142x110 crop %}" alt="Video image"/>
                    </a>
                    <div class="col-xs-12 info">
                        <div class="coll-front-name-content">
                            <a href="{{ bookmark.post.get_absolute_url }}" title="{{ bookmark.post.title}}">{{ bookmark.post.title|truncatechars:50 }}</a>
                        </div> 
                        <a class="coll-front-name-content collection" href="{{ bookmark.post.collection.get_absolute_url }}" title="{{ bookmark.post.collection.name }}">{{ bookmark.post.collection.name|truncatechars:35 }}</a>
                        <div class="row details text-center">
                            <div class="col-xs-4">
                                <p>{{ bookmark.post.duration }}</p> <span>Length</span>
                            </div>
                            <div class="col-xs-4 nviews">
                                <p>{{ bookmark.post.views }}</p> <span>Views</span>
                            </div>
                            <div class="col-xs-4">
                                <p>{{ bookmark.post.rating }}%</p>
                                <span>Rating</span>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            
                    {% empty %}
            <li>There are no videos here, yet.</li>
                    {% endfor %}
        </ul>
{% else %}
    <ul class="random-playlist">
    {% for bookmark in bookmarks %}
        <li class="playlist-content">
            <div class="play-pic-content">
                <a class="text-center playallmain" href="{{ bookmark.post.videos.all.0.get_absolute_url }}?pl={{ bookmark.post.id }}"><span class="glyphicon glyphicon-play"></span> Play all</a>
                <img src="{% thumbnail bookmark.post.videos.all.0.picture 144x110 crop %}" alt="First playlist image"/>
                <div class="sidebar">
                    <p class="text-center">{% with videos=bookmark.post.videos.count %} {{ videos }}{% endwith %}<br/>Videos</p>
                    <img src="{% thumbnail bookmark.post.videos.all.1.picture 42x31 crop %}" class="mini" alt="Second playlist image"/>
                    <img src="{% thumbnail bookmark.post.videos.all.2.picture 42x31 crop %}" class="mini" alt="Third playlist image"/>
                </div>
            </div>
            <div class="play-name-content">
                <a href="{{ bookmark.post.videos.all.0.get_absolute_url }}?pl={{ bookmark.post.id }}" title="{{ bookmark.post.title }}">{{ bookmark.post.title|truncatechars:40 }}</a>
            </div>
            <div class="play-detail-content">
                <div class="row text-center">
                    <div class="col-xs-6">
                        <span>Bookmarks</span> <p>{{ bookmark.post.bookmarks_count }}</p>
                    </div>
                    <div class="col-xs-6">
                       <span class="user-header">User</span><a href="{{bookmark.post.profile.get_absolute_url}}">{{ bookmark.post.profile.user.username }}</a>
                    </div> 
                </div>
            </div>
        </li>
 
    {% empty %}
        <li><div class="alert alert-warning">You have no playlists, yet.</div></li>
    {% endfor %}
    </ul>
{% endif %}

    
</div>
{% endblock %}

comedylib/templates/profiles/menu.html
<navprofile>
	<ul>
		<li id="menu">
			<a id="menu-trigger" href="#">
				<p>Hi,  <span>{{ user.username }} </span> </p>
			</a>
			<div id="menu-content">
				<ul>
            <li><a href="{{ user.profile.get_absolute_url }}" ><span class="profile-icon">Profile</span></a></li>
            <li><a href="{% url settings %}" class="icon-button"><span class="settings-icon">Settings</span></a></li>
            <li><a href="{% url accounts_logout %}" class="icon-button"><span class="logout-icon">Logout</span></a></li>
				</ul>
			</div>                     
		</li>
		
	</ul>
</navprofile>
<script>
var mouse_is_inside = false;
$(document).ready(function(){
	$('#menu-trigger').click(function(){
		var loginBox = $("#menu-content");
        if (loginBox.is(":visible"))
            loginBox.fadeOut("fast");
        else
            loginBox.fadeIn("fast");
        return false;	
		})
	   $("#menu-content").hover(function(){ 
        mouse_is_inside=true; 
    }, function(){ 
        mouse_is_inside=false; 
    });	
	 $("body").click(function(){
        if(! mouse_is_inside) $("#menu-content").fadeOut("fast");
    });	
});
</script>


     
      


comedylib/templates/profiles/playlist_detail.html
{% extends "profiles/playlists.html" %}
{% block title %}Comedylib - Playlists of {{user.username}}{% endblock %}
{% block profile_content %}
{% load thumbnail %}
<script type='text/javascript' src='{{ STATIC_URL }}js/notify.js'></script> 
<div class="col-xs-12 col-sm-10" data-playlist-id={{ playlist.id }}>
    <h5>{{ playlist.title }}</h5>
    <div class="row">
        <div class="col-xs-12">
            <h1 class="text-center">Update playlist name</h1>
            <form id="playlistform" action="{% url edit_playlist playlist.slug playlist.id %}" method="post">{% csrf_token %}
                <input id="id_title" type="text" name="title" maxlength="255" value="{{ playlist.title }}">
                <input type="submit" id="sub" value="Save" class="playlist-input" />
            </form>
        </div>
        <div class="col-xs-12">
            
            <div class="section group playlist-edit"> 
                <ul id="sortable" class="connectedSortable random-video">
                    <li class="collection-front-content li-disabled" >
                        <p class="text-center">Drag &amp; drop to re-arrange the videos</p>
                    </li>
                    {% for pl_item_id, video in videos %}
                        <li class="collection-front-content" data-video-id="{{ video.id }}" id="vid{{ pl_item_id }}">
                            <a id="removebtn" data-video-id="{{ video.id }}" data-pl-item-id="{{ pl_item_id }}" data-toggle="tooltip" class="remove" href="#" rel="tooltip" title="Delete video"><span class="glyphicon glyphicon-trash"></span></a>
                            <a href="{{ video.get_absolute_url }}" class="col-xs-4">
                                    <img src="{% thumbnail video.picture 97x92 crop %}" alt="Video image"/>
                            </a>
                            <div class="col-xs-8 info">
                                <div class="coll-front-name-content">
                                    <a href="{{ video.get_absolute_url }}" title="{{ video.title}}">{{ video.title|truncatechars:56 }}</a>
                                </div> 
                                <a class="coll-front-name-content collection" href="{{ video.collection.get_absolute_url }}" title="{{ video.collection.name }}">{{ video.collection.name|truncatechars:26 }}</a>
                                <div class="row details text-center">
                                    <div class="col-xs-4">
                                        <p>{{ video.duration }}</p><span>Length</span>
                                    </div>
                                    <div class="col-xs-4">
                                        <p>{{ video.views }}</p> <span>Views</span>
                                    </div>
                                    <div class="col-xs-4">
                                        <p>{{ video.rating }}%</p>
                                        <span>Rating</span>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <li>This playlist has no videos.</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-xs-12">
            <form id="playlistform" action="{% url edit_playlist playlist.slug playlist.id %}" method="post">{% csrf_token %}
                <div class="playlist-input"><input type="submit" id="sub" value="Save"  /></div>
            </form>
        </div>
    </div>
<script>

    $(function() {
        $("#sortable").sortable({connectWith: ".connectedSortable", placeholder: "collection-front-content-transparent",items: "li:not(.li-disabled)",distance: 15});
        $("#sortable").disableSelection();
    });
       
    $(document).on("click", ".playlist-input", function(event) {
     
        $.notify("Saved", "success", { position:"top center"}
        );
    });
    $(document).on("click", "#removebtn", function(event) {
        event.preventDefault();
        var r = confirm("Are you sure you want to delete the video from this playlist?");
        if (r === true) {
            a = $(this);
            $.post('{% url remove_from_playlist %}',
                    {'pl_item_id': a.attr('data-pl-item-id'), 'pid': {{ playlist.id }} },
                    function(data) { $('#vid'+a.attr('data-pl-item-id')).slideUp('normal'); });
            return false;
        }
    });
    $(document).on("submit", "#playlistform", function(event) {
        event.preventDefault();
        var update_data = {
            video_order: $('#sortable').sortable('toArray', {attribute: 'data-video-id'}),
            playlist_id: $('.playlist').attr('data-playlist-id'),
            playlist_title: $('#id_title').val()
        },
            url = $('#playlistform').attr('action');
        $.post(url, update_data, function(data) {});
    });
    $(function(){
       $('[rel="tooltip"]').tooltip();
    });
</script>
</div>
{% endblock %}

comedylib/templates/profiles/playlists.html
{% extends "profiles/home.html" %}
{% block title %}Comedylib - {{ user.username }}'s playlists{% endblock %}
{% block profile_content %}
<div class="col-xs-12 col-sm-10">
    {% if user.profile == profile %}
        <h5>Create playlist</h5>
        <form id="playlistform" action="{% url create_playlist %}" method="post">{% csrf_token %}
            <input id="id_title" type="text" name="title" maxlength="255" placeholder="Type the playlist name">
            <input type="submit" id="sub" value="Create playlist" />
             <div class="feedback"><p id="feedback" class="helptextred"> </p></div>
        </form>
    {% endif %}
    <h5>Playlists</h5>
    <ul class="random-playlist">
        {% for playlist in playlists %}
            {% with videos=playlist.videos.playlist_order %}
                <li class="playlist-content"{% if user.profile == profile %} id="play{{ playlist.id }}"{% endif %}>
                    {% include 'profiles/partials/playlist.html' %}
                </li>
            {% endwith %}
        {% empty %}
            <li><div class="alert alert-warning">No playlists found.</div></li>
        {% endfor %}
    </div>
</div>
<script>
    $(document).on("click", "#deletebtn", function(event) {
        event.preventDefault();
        var r=confirm("Are you sure you want to delete this playlist?");
        if (r==true) {
            a = $(this);
            $.post('{% url delete_playlist %}', {'pid': a.attr('data-playlist-id') }, function(data) {
                $('#play'+a.attr('data-playlist-id')).fadeOut(); 
            });
            return false;
        }
    });
    $(function(){
        $('[rel="tooltip"]').tooltip();
    });
</script>
{% endblock %}

comedylib/templates/profiles/settings.html
{% extends "profiles/home.html" %}
{% block title %}Comedylib - Settings page{% endblock %}
{% block profile_content %}
    <div class="col-xs-12 col-sm-10">
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#info" data-toggle="tab">Change your info</a></li>
            <li><a href="#pass" data-toggle="tab">Change your password</a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane fade in active" id="info">
                <form enctype="multipart/form-data" method="post" action="{% url settings %}" class="form">{% csrf_token %}
                    {{ profile_form.non_field_errors }}
                    <div id="fieldWrapper">
                        {{ profile_form.picture.errors }}
                        <label>Picture</label>
                        <p><input type="file" name="picture" id="id_picture" /><span>Select only .jpg, .jpeg, .png or .gif format</span></p>    
                    </div>
                    <div id="fieldWrapper">
                        {{ profile_form.description.errors }}
                        <label>Stuff you want people to know about you</label>
                        <p><textarea name="description" id="id_description" rows="5">{{ profile_form.description.value|default_if_none:""}}</textarea></p> 
                    </div>
                    <div id="fieldWrapper">
                        {{ profile_form.name.errors }}
                        <label>What they call you</label>
                        <p><input type="text" name="name" id="id_name" value="{{ profile_form.name.value|default_if_none:"" }}" /></p> 
                    </div>
                    <div id="fieldWrapper">
                        {{ profile_form.gender.errors }}
                        <label>Gender</label>
                        <p>{{ profile_form.gender }}</p> 
                    </div>
                    <div id="fieldWrapper">
                        {{ profile_form.location.errors }}
                        <label>Where you at</label>
                        <p><input type="text" name="location" id="id_location" value="{{ profile_form.location.value|default_if_none:"" }}" class="st" /></p> 
                    </div>
                    <input type="submit" value="Update" />
                </form>
            </div>
            <div class="tab-pane fade" id="pass">
                <form method="post" action="{% url settings %}" class="form">{% csrf_token %}
                    {{ password_form.non_field_errors }}
                    <div id="fieldWrapper">
                        {{ password_form.old_password.errors }}
                    </div>
                    <p><input type="password" name="old_password" id="id_old_password" placeholder="Old Password" /></p>
                   <div id="fieldWrapper">
                        {{ password_form.new_password1.errors }}
                   </div>
                    <p><input type="password" name="new_password1" id="id_new_password1" placeholder="New Password" /></p>
                    <div id="fieldWrapper">
                        {{ password_form.new_password2.errors }}
                    </div>
                    <p><input type="password" name="new_password2" id="id_new_password2" placeholder="Confirm Password" /> <span class="helptextdark">Enter the same password as above, for verification.</span></p>
                    <input type="submit" value="Update"/>
                </form>
            </div>
        </div>
        <script>
            $(function () {
                $('#myTab a:first').tab('show')
            })
        </script>
    </div>
{% endblock %}